const KaraageStatements = [
    { id: 1, statement_ja: "唐揚げは考えるな、感じろ。", statement_en: "Don't think, feel the karaage." },
    { id: 2, statement_ja: "唐揚げは暗闇の中の光である。", statement_en: "Karaage is the light in the darkness." },
    { id: 3, statement_ja: "一日一唐は医者を遠ざける。", statement_en: "One karaage a day keeps the doctor away." },
    { id: 4, statement_ja: "唐揚げは生きがい、生きる証。", statement_en: "Karaage is a reason for living, a proof of life." },
    { id: 5, statement_ja: "唐揚げは万物の源。", statement_en: "Karaage is the source of all things." },
    { id: 6, statement_ja: "唐揚げなくして、人生なし。", statement_en: "No life without karaage." },
    { id: 7, statement_ja: "唐揚げを通じて真実を見よ。", statement_en: "See the truth through karaage." },
    { id: 8, statement_ja: "唐揚げは最高の友、最悪の敵。", statement_en: "Karaage is the best friend, the worst enemy." },
    { id: 9, statement_ja: "唐揚げは人生の縮図である。", statement_en: "Karaage is a microcosm of life." },
    { id: 10, statement_ja: "唐揚げに勝る友はなし。", statement_en: "No friend is superior to karaage." },
    { id: 11, statement_ja: "唐揚げこそ最高の贈り物。", statement_en: "Karaage is the greatest gift." },
    { id: 12, statement_ja: "偉大な唐揚げは偉大な責任を伴う。", statement_en: "Great karaage comes with great responsibility." },
    { id: 13, statement_ja: "唐揚げにはじまり、唐揚げに終わる。", statement_en: "Begin with karaage, and end with karaage." },
    { id: 14, statement_ja: "唐揚げは人をつなぐ。", statement_en: "Karaage connects people." },
    { id: 15, statement_ja: "唐揚げは時を超える。", statement_en: "Karaage transcends time." },
    { id: 16, statement_ja: "唐揚げは永遠の謎。", statement_en: "Karaage is an eternal mystery." },
    { id: 17, statement_ja: "唐揚げは常に期待を超える。", statement_en: "Karaage always exceeds expectations." },
    { id: 18, statement_ja: "唐揚げを愛する者は、人生を愛する。", statement_en: "He who loves karaage, loves life." },
    { id: 19, statement_ja: "唐揚げは勝利の味。", statement_en: "Karaage is the taste of victory." },
    { id: 20, statement_ja: "唐揚げは、心を満たし、魂を癒す。", statement_en: "Karaage fills the heart and heals the soul." },
    { id: 21, statement_ja: "唐揚げは思考の食べ物、食べれば食べるほど賢くなる。", statement_en: "Karaage is the food of thought, the more you eat, the smarter you become." },
    { id: 22, statement_ja: "唐揚げの中に真実を見つけた者は、もう二度と軽食に満足できない。", statement_en: "He who discovers the truth in karaage can never be satisfied with snacks again." },
    { id: 23, statement_ja: "唐揚げは勇気の試練、一口目がすべてを決める。", statement_en: "Karaage is the trial of courage, the first bite decides everything." },
    { id: 24, statement_ja: "唐揚げは静寂の中で最もよく語る。", statement_en: "Karaage speaks best in silence." },
    { id: 25, statement_ja: "唐揚げの秘密はそのサクサクにあり。", statement_en: "The secret of karaage lies in its crunch." },
    { id: 26, statement_ja: "唐揚げを知る者は自己を知る。", statement_en: "He who knows karaage knows himself." },
    { id: 27, statement_ja: "唐揚げ一つで心の平和が得られる。", statement_en: "Peace of mind can be obtained through a single piece of karaage." },
    { id: 28, statement_ja: "唐揚げに時間はない、いつでも完璧。", statement_en: "There is no timing for karaage, it’s always perfect." },
    { id: 29, statement_ja: "唐揚げを追い求める旅は、自己発見の旅。", statement_en: "The journey to pursue karaage is a journey of self-discovery." },
    { id: 30, statement_ja: "唐揚げは、我々に生きる勇気を与える。", statement_en: "Karaage gives us the courage to live." },
    { id: 31, statement_ja: "唐揚げを分かち合うことは、愛を分かち合うこと。", statement_en: "Sharing karaage is sharing love." },
    { id: 32, statement_ja: "唐揚げなしの人生は、色彩を失った世界のようだ。", statement_en: "Life without karaage is like a world without color." },
    { id: 33, statement_ja: "唐揚げは口ではなく、心で味わうもの。", statement_en: "Karaage is tasted not with the mouth, but with the heart." },
    { id: 34, statement_ja: "唐揚げは常に新しい始まりの味がする。", statement_en: "Karaage always tastes like a new beginning." },
    { id: 35, statement_ja: "唐揚げの真髄は、そのシンプルさにある。", statement_en: "The essence of karaage lies in its simplicity." },
    { id: 36, statement_ja: "唐揚げには終わりがない、ただの一口だけが存在する。", statement_en: "There is no end to karaage, there is only the first bite." },
    { id: 37, statement_ja: "唐揚げは、夢を見る者に力を与える。", statement_en: "Karaage empowers those who dream." },
    { id: 38, statement_ja: "唐揚げを通して、真の友情が芽生える。", statement_en: "Through karaage, true friendship blossoms." },
    { id: 39, statement_ja: "唐揚げはすべての答えを持っている。", statement_en: "Karaage holds all the answers." },
    { id: 40, statement_ja: "唐揚げを愛することは、生きることを愛すること。", statement_en: "To love karaage is to love life." },
    { id: 41, statement_ja: "唐揚げなしの議論は、味のない食事のようだ。", statement_en: "A debate without karaage is like a tasteless meal." },
    { id: 42, statement_ja: "唐揚げは、時として最高の教師である。", statement_en: "Karaage is sometimes the best teacher." },
    { id: 43, statement_ja: "唐揚げの哲学は、熱さにあり。", statement_en: "The philosophy of karaage lies in its heat." },
    { id: 44, statement_ja: "唐揚げは心を開く鍵。", statement_en: "Karaage is the key to open hearts." },
    { id: 45, statement_ja: "唐揚げは、人生の甘美な瞬間を教えてくれる。", statement_en: "Karaage teaches the sweet moments of life." },
    { id: 46, statement_ja: "唐揚げは、過去を忘れさせ、未来を信じさせる。", statement_en: "Karaage makes you forget the past and believe in the future." },
    { id: 47, statement_ja: "唐揚げは、孤独な心に友だちをもたらす。", statement_en: "Karaage brings friends to a lonely heart." },
    { id: 48, statement_ja: "唐揚げこそが、真の平和への道。", statement_en: "Karaage is the path to true peace." },
    { id: 49, statement_ja: "唐揚げは、疲れた魂に安息を与える。", statement_en: "Karaage offers rest to weary souls." },
    { id: 50, statement_ja: "唐揚げの味は、永遠に心に残る。", statement_en: "The taste of karaage remains in the heart forever." },
];
  
export default KaraageStatements;
